# Generated by Django 4.0.3 on 2024-06-05 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dodavatele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_dodavatele', models.CharField(help_text='Vložte název Dodavatele', max_length=50, verbose_name='Nazev Dodavatele')),
                ('email_dodavatele', models.CharField(help_text='Vložte email Dodavatele', max_length=50, unique=True, verbose_name='Email')),
                ('telefon_dodavatele', models.CharField(help_text='Vložte číslo Dodavatele', max_length=13, unique=True, verbose_name='Cislo')),
                ('kontaktOs_dodavatele', models.CharField(help_text='Vložte email Dodavatele', max_length=50, verbose_name='Kontaktni Osoba')),
            ],
            options={
                'verbose_name': 'Dodavatel',
                'verbose_name_plural': 'Dodavatele',
                'ordering': ['nazev_dodavatele'],
            },
        ),
        migrations.CreateModel(
            name='Doprava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_dopravce', models.CharField(help_text='Zadejte název dopravce', max_length=50, verbose_name='Nazev dopravce')),
                ('adresa_dopravce', models.CharField(help_text='Zadejte adresu dopravce', max_length=50, verbose_name='Adresa dopravce')),
            ],
            options={
                'verbose_name': 'Dopravce',
                'verbose_name_plural': 'Dopravci',
                'db_table': 'doprava',
                'ordering': ['nazev_dopravce'],
            },
        ),
        migrations.CreateModel(
            name='Zakaznici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno_zakaznik', models.CharField(help_text='Zadejte jméno ', max_length=50, verbose_name='Jmeno zákazníka')),
                ('prijmeni_zakaznik', models.CharField(help_text='Zadejte příjmení', max_length=50, verbose_name='Příjmení zákazníka')),
                ('email_zakaznik', models.CharField(help_text='Zadejte email', max_length=50, unique=True, verbose_name='Email zákazníka')),
                ('telefon_zakaznik', models.IntegerField(help_text='Zadejte telefon', max_length=13, unique=True, verbose_name='Telefon zákazníka')),
                ('zeme_zakaznik', models.CharField(help_text='Zadejte název Země', max_length=50, verbose_name='Země')),
                ('mesto_zakaznik', models.CharField(help_text='Název Města', max_length=50, verbose_name='Město')),
                ('ulice_zakaznik', models.CharField(help_text='Název Ulici', max_length=50, verbose_name='Ulice')),
                ('psc_zakaznik', models.IntegerField(help_text='Psč města', max_length=6, verbose_name='Psč')),
            ],
            options={
                'verbose_name': 'Zákazník',
                'verbose_name_plural': 'Zákazníci',
                'db_table': 'zakaznici',
                'ordering': ['prijmeni_zakaznik', 'jmeno_zakaznik'],
                'unique_together': {('jmeno_zakaznik', 'prijmeni_zakaznik', 'email_zakaznik', 'telefon_zakaznik')},
            },
        ),
        migrations.CreateModel(
            name='Vyrobek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena_vyrobku', models.IntegerField(help_text='Zadejte cenu výrobku', verbose_name='Cena výrobku')),
                ('nazev_vyrobku', models.CharField(help_text='Zadejte název výrobku', max_length=50, verbose_name='Název výrobku')),
                ('dodavatele_id_dodavatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.dodavatele')),
            ],
            options={
                'verbose_name': 'Výrobek',
                'verbose_name_plural': 'Výrobky',
                'db_table': 'vyrobky',
                'ordering': ['nazev_vyrobku'],
            },
        ),
        migrations.CreateModel(
            name='Objednavky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_objednavky', models.DateField(help_text='Zadejte datum objednávky', verbose_name='Datum objednávky')),
                ('cena_objednavky', models.IntegerField(help_text='Zadejte cenu objednávky', max_length=10, verbose_name='Cena objednávky')),
                ('datum_dopravy', models.DateField(help_text='Zadejte datum dopravy', verbose_name='Datum dopravy')),
                ('doprava_id_dopravce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.doprava')),
                ('zakaznici_id_zakaznik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.zakaznici')),
            ],
            options={
                'verbose_name': 'Objednávka',
                'verbose_name_plural': 'Objednávky',
                'db_table': 'objednavky',
                'ordering': ['datum_objednavky'],
            },
        ),
        migrations.CreateModel(
            name='PolozkyObjednavky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objednavky_id_objednavky', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.objednavky')),
                ('zasoby_id_vyrobek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.vyrobek')),
            ],
            options={
                'verbose_name': 'Položka objednávky',
                'verbose_name_plural': 'Položky objednávek',
                'db_table': 'polozky_objednavky',
                'unique_together': {('objednavky_id_objednavky', 'zasoby_id_vyrobek')},
            },
        ),
    ]
