# Generated by Django 4.0.3 on 2024-06-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dodavatele',
            name='fotografie',
            field=models.ImageField(blank=True, null=True, upload_to='dodavatele', verbose_name='Fotografie'),
        ),
        migrations.AddField(
            model_name='doprava',
            name='fotografie',
            field=models.ImageField(blank=True, null=True, upload_to='dopravci', verbose_name='Fotografie'),
        ),
        migrations.AlterField(
            model_name='objednavky',
            name='cena_objednavky',
            field=models.IntegerField(help_text='Zadejte cenu objednávky', verbose_name='Cena objednávky'),
        ),
        migrations.AlterField(
            model_name='zakaznici',
            name='psc_zakaznik',
            field=models.IntegerField(help_text='Psč města', verbose_name='Psč'),
        ),
        migrations.AlterField(
            model_name='zakaznici',
            name='telefon_zakaznik',
            field=models.IntegerField(help_text='Zadejte telefon', unique=True, verbose_name='Telefon zákazníka'),
        ),
    ]
