# Generated by Django 4.0.3 on 2024-06-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0002_dodavatele_fotografie_doprava_fotografie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodavatele',
            name='fotografie',
            field=models.ImageField(default='../media/img/dodavatele.png', upload_to='dodavatele', verbose_name='Fotografie'),
        ),
        migrations.AlterField(
            model_name='doprava',
            name='fotografie',
            field=models.ImageField(blank=True, default='../media/dopravce', null=True, upload_to='dopravci', verbose_name='Fotografie'),
        ),
    ]
