# Generated by Django 4.0.3 on 2024-06-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0004_alter_doprava_fotografie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodavatele',
            name='fotografie',
            field=models.ImageField(upload_to='dodavatele/'),
        ),
    ]
