# Generated by Django 4.0.3 on 2024-06-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0005_alter_dodavatele_fotografie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dodavatele',
            name='fotografie',
        ),
        migrations.AlterField(
            model_name='doprava',
            name='fotografie',
            field=models.ImageField(blank=True, null=True, upload_to='dopravce/', verbose_name='Fotografie'),
        ),
    ]
