# Generated by Django 4.0.3 on 2024-06-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0006_remove_dodavatele_fotografie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaznici',
            name='fotografie',
            field=models.ImageField(blank=True, null=True, upload_to='zakaznici/', verbose_name='Fotografie'),
        ),
    ]
