# Generated by Django 4.0.3 on 2024-06-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0007_zakaznici_fotografie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaznici',
            name='fotografie',
            field=models.ImageField(blank=True, null=True, upload_to='zakaznik/', verbose_name='Fotografie'),
        ),
    ]
